// <auto-generated />
using GlouriousGamesEcommerce.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GloriousGamesEcommerce.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221221152549_SeedProductsToDatabase")]
    partial class SeedProductsToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GloriousGamesEcommerce.Services.ProductAPI.Models.Dto.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Switch",
                            Description = "Embark on a new Pokémon adventure.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/1.jpg",
                            Name = "Pokémon Violet",
                            Price = 79.959999999999994
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Switch",
                            Description = "Hogwarts Legacy is an open-world action RPG set in the world introduced in the Harry Potter books.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/2.jpg",
                            Name = "Hogwarts Legacy Deluxe",
                            Price = 89.959999999999994
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Switch",
                            Description = "Worlds are colliding in Sonic the Hedgehog's newest high-speed adventure!",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/3.jpg",
                            Name = "Sonic Frontiers",
                            Price = 79.959999999999994
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Xbox One",
                            Description = "Enjoy a more true-to-life football experience in FIFA 23 with new gameplay features that create risk-versus-reward shooting, new free kick, penalty, and corner mechanics, and more football variety.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/4.jpg",
                            Name = "FIFA 23",
                            Price = 49.960000000000001
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Xbox One",
                            Description = "Over twenty years ago in harran, we fought the virus—and lost. Now, we’re losing again.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/5.jpg",
                            Name = "Dying Light 2",
                            Price = 39.950000000000003
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Xbox One",
                            Description = "Cyberpunk 2077 has several updates planned for the new year that are planned to address a number of the issues that users have faced in the game.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/6.jpg",
                            Name = "Cyberpunk 2077",
                            Price = 39.859999999999999
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "PS4",
                            Description = "Witness what makes Task Force 141 the legendary squad it is today in Call of Duty: Modern Warfare II.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/7.jpg",
                            Name = "Call Of Duty Modern Warfare 2",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "PS4",
                            Description = "Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/8.jpg",
                            Name = "God of War Ragnarök",
                            Price = 79.989999999999995
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "PS4",
                            Description = "FINAL FANTASY VII – REUNION is a remaster of CRISIS CORE, featuring a complete HD graphics overhaul, remastered soundtrack, and an updated combat system.",
                            ImageUrl = "https://gloriousgamesecommerce.blob.core.windows.net/gloriousgames/9.jpg",
                            Name = "Final Fantasy VII Reunion",
                            Price = 64.959999999999994
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
